default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: <%= ENV.fetch("MYSQL_DB") { '' } %> #.env 環境変数を参照
  username: <%= ENV.fetch("MYSQL_USER") { '' } %> #.env 環境変数を参照
  password: <%= ENV.fetch("MYSQL_ROOT_PASSWORD") { '' } %> #.env 環境変数を参照
  host: db #docker-compose.ymlのDBのサービス名を指定

# command rails db:create:sub

development:
  primary:
    <<: *default
    database: <%= ENV.fetch("MYSQL_DB") { '' } %>_development #.env 環境変数を参照
    adapter: mysql2
#    port: 33061
  primary_replica:
    <<: *default
    database: <%= ENV.fetch("MYSQL_DB") { '' } %>_replica_development #.env 環境変数を参照
    adapter: mysql2
#    port: 33062
    replica: true
  sub:
    <<: *default
    database: <%= ENV.fetch("MYSQL_DB") { '' } %>_sub_development #.env 環境変数を参照
    migrations_paths: db/sub_migrate

test:
  <<: *default
  database: <%= ENV.fetch("MYSQL_DB") { '_test' } %>_test #.env 環境変数を参照

# production　プロジェクトに合わせて修正。
production:
  <<: *default
  database: app_production
  username: app
  password: <%= ENV["APP_DATABASE_PASSWORD"] %>

# example replica
# 1 .primaryとprimary_replicaのデータベース名は同じにすべきです。
#    primaryとreplicaが同じデータを持つからです.(database my_primary_database)
# 2 writerとreplicaでは異なるデータベースユーザー名を使いかつreplicaのパーミッションは（writeではなく）readのみにすべきです。
#
#  option schema_dump: false
#
#  primary:
#    database: my_primary_database
#    username: root
#    password: <%#= ENV['ROOT_PASSWORD'] %>
#    adapter: mysql2
#  primary_replica:
#    database: my_primary_database
#    username: root_readonly
#    password: <%#= ENV['ROOT_READONLY_PASSWORD'] %>
#    adapter: mysql2
#    replica: true